### ISSUE TITLE
Broken dependency on humanize_time

### ISSUE THREAD

**Issue by s0r00t** [fisherman/sektor#1]
Install fails because this dependency does not exists anymore.
sektor install itself even if the dependency is missing, breaking fish.

**Comment by bucaran** [comment]
@s0r00t Yes, sektor, has been on hold for a while, but I should be able to get back to it soon. Thanks for reporting this.

**Comment by bucaran** [comment]
Just updated the dependency, but something other may be broken. I'll get back to this soon.

**Comment by bucaran** [comment]
@s0r00t Finally, Sektor is ready. Sorry, for taking forever :)

<img width="1280" alt="screen shot 2016-05-11 at 4 49 45 am" src="https://cloud.githubusercontent.com/assets/8317250/15160287/e3edc432-1733-11e6-970b-a5562f1b7688.png">
