### ISSUE TITLE
Failed to test CMDDURATION at right prompt

### ISSUE THREAD

**Issue by Alsan** [fisherman/sektor#2]
Hello, I got an error message when the shell starts. The error message is as following:
```
 test returned eval errors:
             invalid integer ''
```

After some investigation, I found that the problem is caused by the line 18 of fish_right_prompt.fish:
```
if test "$CMD_DURATION" -gt 100
   ...
```

After changing the line to something like:
```
if test ! -z "$CMD_DURATION"
   ...
```
the problem was gone.

The change is meaningless, just prevent the error. I'm not too familiar with the syntax of the fish shell script, and therefore, I couldn't fix the problem as it should be.

**Comment by jorgebucaran** [comment]
Fixed in https://github.com/fisherman/sektor/commit/41b519e3cedd0dd77dfd03a8a5c5d12552b36c6a.
